@extends('User.partials.auth-layout')
@section('title', 'Đăng ký')
@section('intro', 'Tạo tài khoản để đặt hàng và theo dõi đơn của bạn.')
@section('auth-content')
<form id="loginForm"><div class="mb-3"><label for="yourName" class="form-label">Họ và tên</label><input id="yourName" name="name" type="text" autocomplete="name" class="form-control" required maxlength="255"></div>
<div class="mb-3"><label for="yourEmail" class="form-label">Email</label><input id="yourEmail" name="email" type="email" autocomplete="email" class="form-control" required ></div>
<div class="mb-3"><label for="yourPhone" class="form-label">Số điện thoại</label><input id="yourPhone" name="phone" type="tel" autocomplete="tel" class="form-control" required pattern="0[35789][0-9]{8}" title="Số điện thoại Việt Nam gồm 10 chữ số"></div>
<div class="mb-3"><label for="yourPassword" class="form-label">Mật khẩu</label><div class="pc-password-field"><input id="yourPassword" name="password" type="password" autocomplete="new-password" class="form-control" required minlength="8" aria-describedby="password-hint"><button type="button" class="pc-password-toggle" data-password-toggle="yourPassword" aria-controls="yourPassword" aria-pressed="false">Hiện</button></div></div>
<p id="password-hint" class="small pc-auth-intro">Ít nhất 8 ký tự. Nên kết hợp chữ, số và ký hiệu.</p><div class="mb-3"><label for="yourConfirmPassword" class="form-label">Nhập lại mật khẩu</label><div class="pc-password-field"><input id="yourConfirmPassword" name="password_confirmation" type="password" autocomplete="new-password" class="form-control" required minlength="8"><button type="button" class="pc-password-toggle" data-password-toggle="yourConfirmPassword" aria-controls="yourConfirmPassword" aria-pressed="false">Hiện</button></div></div>
<p class="pc-auth-feedback d-none" data-feedback role="status" aria-live="polite"></p><button type="submit" class="btn btn-primary w-100" id="FormRegisterUserButton">Gửi mã xác nhận</button></form><p class="mt-4 mb-0">Đã có tài khoản? <a href="{{ route('user.login') }}">Đăng nhập</a></p><div class="modal fade" id="OTP" tabindex="-1" aria-labelledby="otp-title" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title h5" id="otp-title">Xác nhận email</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Đóng"></button></div><form id="otp-form"><div class="modal-body"><p>Nhập mã vừa được gửi tới <strong id="otp-email"></strong>. Kiểm tra thư rác nếu chưa thấy email.</p><div class="mb-3"><label for="yourOTP" class="form-label">Mã xác nhận</label><input id="yourOTP" name="OTP" type="text" autocomplete="one-time-code" class="form-control" required inputmode="numeric"></div>
<p class="pc-auth-feedback d-none" data-feedback role="status" aria-live="polite"></p></div><div class="modal-footer"><button type="submit" id="submitOTP" class="btn btn-primary">Tạo tài khoản</button></div></form></div></div></div>
@endsection
@section('auth-script')
@vite('resources/js/User/account/create.js')
@endsection
